apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/application: serverless-operator-140
    appstudio.redhat.com/component: kn-plugin-func-func-util-123
  name: kn-plugin-func-func-util-123
spec:
  image:
    name: serverless-operator-140/kn-plugin-func-func-util
    visibility: public
